//! Weights measured against this runtime. Regenerated by
//! `.maintain/run-benchmarks.sh`, do not edit by hand.

pub mod frame_system_extensions;
pub mod frame_system;
pub mod pallet_balances;
pub mod pallet_bounties;
pub mod pallet_conviction_voting;
pub mod pallet_evm;
pub mod pallet_im_online;
pub mod pallet_multisig;
pub mod pallet_preimage;
pub mod pallet_proxy;
pub mod pallet_scheduler;
pub mod pallet_timestamp;
pub mod pallet_transaction_payment;
pub mod pallet_utility;
pub mod pallet_vesting;
